const STORAGE_KEY = 'campus-opportunity-hub-events';
const FAVORITES_KEY = 'campus-opportunity-hub-favorites';

const baseActivities = [
  { id:'A01', title:'2026 新生校园开放日与学院社团招新', source:'官方', sourceType:'official', audience:'全校新生', location:'校本部大礼堂', timeText:'9月20日 15:00', deadline:'2026-09-24 23:59', startAt:'2026-09-20T15:00:00', fit:96, trust:95, risk:'低风险', state:'报名中', stateKey:'active', need:'无需提前准备，直接前往现场登记', details:'由校团委联合各学院举办，包含社团招新、学院介绍和校园生活体验，适合新生快速了解学校资源。', tags:['新生','校园活动','社团'], freshmanOnly:true, lowRisk:true, image:'https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&w=900&q=80', createdAt:'2026-09-10T09:00:00Z' },
  { id:'A02', title:'AI 创新创业训练营报名', source:'学院', sourceType:'college', audience:'计算机相关专业', location:'创新中心 2F', timeText:'9月19日 19:00', deadline:'2026-09-20 18:00', startAt:'2026-09-19T19:00:00', fit:88, trust:84, risk:'低风险', state:'即将截止', stateKey:'urgent', need:'优先面向计算机、人工智能、数字媒体相关专业', details:'包含导师指导、案例分享和团队协作，适合对创新实践和编程项目感兴趣的同学。', tags:['AI','创新','创业'], freshmanOnly:false, lowRisk:true, image:'https://images.unsplash.com/photo-1531482615713-2afd69097998?auto=format&fit=crop&w=900&q=80', createdAt:'2026-09-12T10:30:00Z' },
  { id:'A03', title:'新生志愿者服务岗招募', source:'官方', sourceType:'official', audience:'全校学生', location:'学生事务中心', timeText:'9月18日 10:00', deadline:'2026-09-22 18:00', startAt:'2026-09-18T10:00:00', fit:86, trust:88, risk:'低风险', state:'报名中', stateKey:'active', need:'参与活动组织和接待工作，需按时到岗', details:'由学校统一组织，工作包括迎新接待和活动协助，适合希望早接触校园运营的同学。', tags:['志愿服务','接待','新生'], freshmanOnly:true, lowRisk:true, image:'https://images.unsplash.com/photo-1559027615-cd4628902d4a?auto=format&fit=crop&w=900&q=80', createdAt:'2026-09-08T08:00:00Z' },
  { id:'A04', title:'校外培训班“高薪编程速成”招募', source:'学生发布', sourceType:'student', audience:'不限', location:'线上群聊', timeText:'9月17日 20:00', deadline:'2026-09-21 23:59', startAt:'2026-09-17T20:00:00', fit:64, trust:32, risk:'高风险', state:'待确认', stateKey:'review', need:'需额外缴纳培训费用，宣传语有夸大成分', details:'缺少学校背景和明确组织方信息，承诺“轻松高薪”，请先核实正规资质。', tags:['编程','培训','注意'], freshmanOnly:false, lowRisk:false, image:'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=900&q=80', createdAt:'2026-09-14T13:20:00Z' }
];

const state = { search:'', source:'all', status:'all', freshmanOnly:false, lowRiskOnly:false, sortBy:'priority', favorites:readFavorites() };
const els = {};
document.addEventListener('DOMContentLoaded', init);

function init(){ cacheElements(); bindEvents(); render(); }
function cacheElements(){
  ['searchInput','sortSelect','freshmanOnly','lowRiskOnly','todaySummary','recommendSection','activityList','detailModal','detailContent','closeModalBtn','publishBtn','publishModal','closePublishBtn','publishForm','cancelPublishBtn','favoritesList','clearFavoritesBtn','filterSummary','heroTotal','heroFresh','heroLowRisk'].forEach(k=>els[k]=document.getElementById(k));
  els.sourceButtons=[...document.querySelectorAll('[data-source]')]; els.statusButtons=[...document.querySelectorAll('[data-status]')];
}
function bindEvents(){
  els.searchInput?.addEventListener('input',e=>{state.search=e.target.value.trim();render()});
  els.sourceButtons.forEach(b=>b.addEventListener('click',()=>{state.source=b.dataset.source; setActive(els.sourceButtons,state.source,'source');render()}));
  els.statusButtons.forEach(b=>b.addEventListener('click',()=>{state.status=b.dataset.status; setActive(els.statusButtons,state.status,'status');render()}));
  els.freshmanOnly?.addEventListener('change',e=>{state.freshmanOnly=e.target.checked;render()});
  els.lowRiskOnly?.addEventListener('change',e=>{state.lowRiskOnly=e.target.checked;render()});
  els.sortSelect?.addEventListener('change',e=>{state.sortBy=e.target.value;render()});
  document.getElementById('resetFiltersBtn')?.addEventListener('click',resetFilters);
  els.publishBtn?.addEventListener('click',openPublishModal); els.closePublishBtn?.addEventListener('click',closePublishModal); els.cancelPublishBtn?.addEventListener('click',closePublishModal); els.closeModalBtn?.addEventListener('click',closeDetailModal);
  els.clearFavoritesBtn?.addEventListener('click',()=>{state.favorites=[];saveFavorites();render();toast('收藏夹已清空')});
  document.addEventListener('click',e=>{if(e.target.closest('[data-close="true"]')){closeDetailModal();closePublishModal()} const fav=e.target.closest('[data-favorite-id]'); if(fav){toggleFavorite(fav.dataset.favoriteId);return} const detail=e.target.closest('[data-detail-id]'); if(detail)openDetailModal(detail.dataset.detailId)});
  document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeDetailModal();closePublishModal()}});
  els.publishForm?.addEventListener('submit',e=>{e.preventDefault();submitNewActivity()});
}
function setActive(buttons,value,key){buttons.forEach(b=>b.classList.toggle('active',b.dataset[key]===value))}
function readFavorites(){try{return JSON.parse(localStorage.getItem(FAVORITES_KEY)||'[]').filter(Boolean)}catch{return[]}}
function saveFavorites(){try{localStorage.setItem(FAVORITES_KEY,JSON.stringify(state.favorites))}catch{}}
function readEvents(){try{const x=JSON.parse(localStorage.getItem(STORAGE_KEY)||'[]');return Array.isArray(x)?x:[]}catch{return[]}}
function saveEvents(x){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(x))}catch{}}
function getAllActivities(){const local=readEvents();const ids=new Set(local.map(x=>x.id));return [...local,...baseActivities.filter(x=>!ids.has(x.id))].filter(Boolean)}
function getFilteredActivities(){const q=state.search.toLowerCase();return getAllActivities().filter(a=>{const hay=[a.title,a.source,a.audience,a.details,...(a.tags||[])].join(' ').toLowerCase();return (!q||hay.includes(q))&&(state.source==='all'||a.sourceType===state.source)&&(state.status==='all'||a.stateKey===state.status)&&(!state.freshmanOnly||a.freshmanOnly)&&(!state.lowRiskOnly||a.lowRisk)}).sort(sortActivities)}
function sortActivities(a,b){if(state.sortBy==='trust')return(b.trust||0)-(a.trust||0);if(state.sortBy==='time')return new Date(a.startAt||0)-new Date(b.startAt||0);return((b.fit||0)+(b.trust||0))-((a.fit||0)+(a.trust||0))}
function render(){const list=getFilteredActivities();renderStats();renderSummary(list);renderRecommendations(list);renderList(list);renderFavorites();renderFilterSummary(list)}
function renderStats(){const all=getAllActivities();setText(els.heroTotal,all.length);setText(els.heroFresh,all.filter(a=>a.freshmanOnly).length);setText(els.heroLowRisk,all.filter(a=>a.lowRisk).length)}
function setText(el,value){if(el)el.textContent=value}
function renderSummary(list){if(!els.todaySummary)return;els.todaySummary.innerHTML=`<div class="summary-metric"><strong>${list.length}</strong><span>条符合信息</span></div><div class="summary-metric"><strong>${list.filter(a=>['active','urgent'].includes(a.stateKey)).length}</strong><span>个可参与</span></div><div class="summary-metric"><strong>${list.filter(a=>a.lowRisk).length}</strong><span>个低风险</span></div>`}
function renderFilterSummary(list){if(els.filterSummary)els.filterSummary.innerHTML=state.search||state.source!=='all'||state.status!=='all'||state.freshmanOnly||state.lowRiskOnly?`<span class="filter-summary-badge">当前筛选 ${list.length} 条 · 点击卡片查看详情</span>`:'<span class="filter-summary-empty">已展示全部机会</span>'}
function renderRecommendations(list){if(!els.recommendSection)return;const top=list.slice(0,3);els.recommendSection.innerHTML=top.length?`<div class="recommend-heading"><p class="eyebrow">为你推荐</p><h2>最值得关注的机会</h2></div><div class="recommend-wrap">${top.map(cardHTML).join('')}</div>`:'<div class="empty-state">暂无符合条件的推荐内容，试试重置筛选。</div>'}
function cardHTML(a){return`<article class="recommend-card"><img src="${safe(a.image)}" alt="${safe(a.title)}" loading="lazy"><div class="card-content"><div class="badge-row"><span class="badge ${sourceClass(a.sourceType)}">${safe(a.source)}</span><span class="badge ${a.lowRisk?'safe':'critical'}">${safe(a.risk)}</span></div><h3>${safe(a.title)}</h3><p>${safe(a.details)}</p><button class="text-btn" data-detail-id="${safe(a.id)}">查看详情 →</button></div></article>`}
function renderList(list){if(!els.activityList)return;if(!list.length){els.activityList.innerHTML='<div class="empty-state">没有符合筛选条件的信息</div>';return}els.activityList.innerHTML=list.map(a=>`<article class="activity-card"><img class="activity-image" src="${safe(a.image)}" alt="${safe(a.title)}" loading="lazy"><div class="card-body"><div class="card-top"><div class="badge-row"><span class="badge ${sourceClass(a.sourceType)}">${safe(a.source)}</span><span class="badge ${a.lowRisk?'safe':'critical'}">${safe(a.risk)}</span></div><button class="favorite-btn ${state.favorites.includes(a.id)?'active':''}" data-favorite-id="${safe(a.id)}" aria-label="${state.favorites.includes(a.id)?'取消收藏':'收藏'}">★</button></div><h3 class="card-title">${safe(a.title)}</h3><div class="card-meta"><span>📅 ${safe(a.timeText)}</span><span>📍 ${safe(a.location)}</span><span>适配度 <strong>${a.fit}%</strong> · 可信度 <strong>${a.trust}%</strong></span></div><p>${safe(a.details)}</p><div class="badge-row">${(a.tags||[]).map(t=>`<span class="tag">#${safe(t)}</span>`).join('')}</div><button class="secondary-btn detail-btn" data-detail-id="${safe(a.id)}">查看详情</button></div></article>`).join('')}
function renderFavorites(){if(!els.favoritesList)return;const items=getAllActivities().filter(a=>state.favorites.includes(a.id));els.favoritesList.innerHTML=items.length?items.map(a=>`<div class="favorite-item"><span>${safe(a.title)}</span><button data-detail-id="${safe(a.id)}">查看</button></div>`).join(''):'<p class="empty-favorites">还没有��藏内容，点击机会卡片上的 ★ 收藏。</p>'}
function sourceClass(x){return x==='college'?'college':x==='student'?'student':'official'}
function safe(x){return String(x??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function openDetailModal(id){const a=getAllActivities().find(x=>x.id===id);if(!a||!els.detailModal)return;els.detailContent.innerHTML=`<div class="detail-header"><span class="badge ${sourceClass(a.sourceType)}">${safe(a.source)}</span><h3>${safe(a.title)}</h3><button class="favorite-btn ${state.favorites.includes(a.id)?'active':''}" data-favorite-id="${safe(a.id)}">★ 收藏</button></div><img class="detail-image" src="${safe(a.image)}" alt="${safe(a.title)}"><div class="detail-grid"><div class="detail-block"><h4>时间</h4><p>${safe(a.timeText)}</p></div><div class="detail-block"><h4>地点</h4><p>${safe(a.location)}</p></div><div class="detail-block"><h4>适用对象</h4><p>${safe(a.audience)}</p></div><div class="detail-block"><h4>截止时间</h4><p>${safe(a.deadline)}</p></div></div><p>${safe(a.details)}</p><div class="warning-box">提示：${safe(a.need)}</div>`;els.detailModal.classList.remove('hidden');els.detailModal.setAttribute('aria-hidden','false')}
function closeDetailModal(){els.detailModal?.classList.add('hidden');els.detailModal?.setAttribute('aria-hidden','true')}
function openPublishModal(){els.publishModal?.classList.remove('hidden');els.publishModal?.setAttribute('aria-hidden','false')}
function closePublishModal(){els.publishModal?.classList.add('hidden');els.publishModal?.setAttribute('aria-hidden','true');els.publishForm?.reset()}
function toggleFavorite(id){state.favorites=state.favorites.includes(id)?state.favorites.filter(x=>x!==id):[...state.favorites,id];saveFavorites();render();toast(state.favorites.includes(id)?'已加入收藏':'已取消收藏')}
function submitNewActivity(){const v=id=>document.getElementById(id)?.value.trim()||'';const a={id:`L${Date.now()}`,title:v('newTitle')||'新发布活动',source:v('newSource')||'学生发布',sourceType:'student',audience:v('newAudience')||'全校学生',location:v('newLocation')||'待定',timeText:v('newTime')||'待定',deadline:v('newDeadline')||'待定',startAt:new Date().toISOString(),fit:78,trust:65,risk:'待确认',state:'待确认',stateKey:'review',need:'信息已由用户提交，需人工确认真实性',details:v('newDescription')||'新活动信息已发布。',tags:(v('newTags').split(/[，,\s]+/).filter(Boolean)).slice(0,8),freshmanOnly:true,lowRisk:false,image:'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&w=900&q=80',createdAt:new Date().toISOString()};saveEvents([a,...readEvents()]);closePublishModal();render();toast('发布成功，已加入待确认列表')}
function resetFilters(){state.search='';state.source='all';state.status='all';state.freshmanOnly=false;state.lowRiskOnly=false;if(els.searchInput)els.searchInput.value='';if(els.freshmanOnly)els.freshmanOnly.checked=false;if(els.lowRiskOnly)els.lowRiskOnly.checked=false;setActive(els.sourceButtons,'all','source');setActive(els.statusButtons,'all','status');render()}
function toast(message){let el=document.getElementById('toast');if(!el){el=document.createElement('div');el.id='toast';el.className='toast';document.body.appendChild(el)}el.textContent=message;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),2200)}
window.campusOpportunityHub={readEvents,saveEvents,render,getFilteredActivities,state,toggleFavorite};
